### ISSUE TITLE
Unable to setup deckgrid

### ISSUE THREAD

**Issue by collin35** [akoenig/angular-deckgrid#19]
Hi i followed your instructions but I am simply unable to make it work. This is what my console says. Any ideas please ? Thanks for response.

I have css in my styles.css, also exactly same template just my data object is loaded via $http({method: ... 

angular-deckgrid: No CSS configuration found (see https://github.com/akoenig/angular-deckgrid#the-grid-configuration) angular.js:9101
TypeError: Cannot call method 'match' of undefined
    at c (http://something/js/vendor/angular-deckgrid.min.js:2:1566)
    at http://something/js/vendor/angular-deckgrid.min.js:2:1906
    at Object.p [as forEach](http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:7:307)
    at http://something/js/vendor/angular-deckgrid.min.js:2:1884
    at Array.forEach (native)
    at Object.p [as forEach](http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:7:255)
    at c.$$getMediaQueries (http://something/js/vendor/angular-deckgrid.min.js:2:1843)
    at new c (http://something/js/vendor/angular-deckgrid.min.js:2:1181)
    at Object.create (http://something/js/vendor/angular-deckgrid.min.js:2:3021)
    at b.$$link (http://something/js/vendor/angular-deckgrid.min.js:2:758) <div deckgrid="" source="products" cardtemplate="templates/deckgrid-card.html" class="deckgrid ng-isolate-scope"> angular.js:9101
TypeError: Cannot read property 'length' of undefined
    at c.$$onModelChange (http://something/js/vendor/angular-deckgrid.min.js:2:2851)
    at g.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:98:434)
    at g.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:101:157)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:17:415
    at Object.d [as invoke](http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:30:352)
    at Xb.c (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:17:323)
    at Xb (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:18:30)
    at Rc (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:17:99)
    at HTMLDocument.<anonymous> (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:198:494)
    at j (http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js:2:26676) angular.js:9101
TypeError: Cannot read property 'length' of null
    at c.$$onModelChange (http://something/js/vendor/angular-deckgrid.min.js:2:2851)
    at g.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:98:434)
    at g.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:101:157)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:67:175)
    at Q (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:71:64)
    at XMLHttpRequest.t.onreadystatechange (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:72:27) angular.js:9101
TypeError: Cannot read property 'length' of null
    at c.$$onModelChange (http://something/js/vendor/angular-deckgrid.min.js:2:2862)
    at g.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:98:434)
    at g.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:101:157)
    at g (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:67:175)
    at Q (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:71:64)
    at XMLHttpRequest.t.onreadystatechange (http://ajax.googleapis.com/ajax/libs/angularjs/1.2.1/angular.min.js:72:27)

**Comment by dejavu1987** [comment]
![image](https://cloud.githubusercontent.com/assets/1720245/5799319/01e72860-9ff9-11e4-89b9-33750b1605b6.png)

I am having the same issue. You can see the inclusion of CSS file, HTML tag, and the css definition as well.. But I am getting the css not configured error.

**Comment by dejavu1987** [comment]
Sorry, found the cause. We are using the lazy loaded component approach which loads the css lazily which is causing this. Is there a way we can re-evaluate css in runtime? I dont think this is an issue of this module though any help will be appreciated. Thanx
